entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: myresolver

api:
  dashboard: true
  insecure: false

certificatesResolvers:
  myresolver:
    acme:
      email: yuteenightxi@gmail.com
      storage: acme.json
      httpChallenge:
        entryPoint: web
      caServer: "https://acme-v02.api.letsencrypt.org/directory"

providers:
  docker:
    exposedByDefault: false
    network: app-network