
- name: Create acme.json file for Traefik
  file:
    path: /opt/app/acme.json
    state: touch
    mode: '0600'

- name: Bring up the application stack
  shell: docker-compose up -d
  args:
    chdir: /opt/app