docker_repo_url: "https://download.docker.com/linux/ubuntu"
docker_repo_gpg_key: "/usr/share/keyrings/docker-archive-keyring.gpg"
docker_compose_version: "v2.2.3"
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-compose-plugin